### ISSUE TITLE
[질문] 해커톤 질문있습니다.

### ISSUE THREAD

**Issue by Bae0203** [microsoft/hackers-ground#129]
안녕하세요 해커톤 지원 관련 질문이 있어 글을 작성합니다.

해커톤 팀으로 신청할 수 있는지 물어보고싶습니다.
전에는 팀신청 할수 있었는데 지금은 안떠서 팀끼리 신청이 마감된건지 물어보고 싶습니다.

좋은 하루보내시길 바랍니다.

**Comment by kei01138** [comment]
관련 질문은 디스코드로 부탁드립니다
아래에 링크 첨부합니다

https://aka.ms/hg/discord
