### ISSUE TITLE
[**AZ-900**] 질문있습니다.

### ISSUE THREAD

**Issue by JunBeomHan** [microsoft/hackers-ground#133]
죄송합니다. ㅠㅠ 질문이 있는데 창구가 여기 밖에 없어 챌린지 완료를 위장하여 질문합니다.
팀단위로 신청하기 위해  구글 폼 설문을 참여 하였더니, 팀 단위로 신청하는 선택지가 없어서 질문 드립니다.

[질문 내용]
본 프로그램은 개인 단위로만 신청할 수 있나요? 아니면 팀 단위, 개인 단위로 신청할 수 있나요?
만약 팀 단위, 개인 단위로 신청할 수 있다면 팀 단위는 어떻게 신청할 수 있나요?

**Comment by kei01138** [comment]
관련 질문은 디스코드로 부탁드립니다
아래에 링크 첨부합니다

https://aka.ms/hg/discord
