### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by siksik-Choi** [microsoft/hackers-ground#199]
## 챌린지 디테일

* 깃헙 ID: https://github.com/siksik-Choi

* Microsoft Learn 프로필 링크: https://learn.microsoft.com/ko-kr/users/16500505/
users/53042470/

* 클라우드 스킬 챌린지 토픽/코드: 애저 기초 (AZ-900)

<img width="1167" alt="image" src="https://github.com/microsoft/hackers-ground/assets/80188977/a08d3e62-b6d7-44e9-835b-0bb0ea2ad76f">

**Comment by isp829** [comment]
안녕하세요. 해커그라운드 조직 의원회입니다.
디스코드 참여 부탁드립니다.
https://discord.gg/bnpvGuE2
