### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by lee1010yj** [microsoft/hackers-ground#355]
* 깃헙 ID
https://github.com/lee1010yj
  

* Microsoft Learn 프로필 링크

https://learn.microsoft.com/ko-kr/users/yejinlee-6234/challenges

## 챌린지 완료 인증 

![image](https://github.com/microsoft/hackers-ground/assets/136915325/25eacb12-8fae-4bc6-a888-825aa00242fd)

**Comment by isp829** [comment]
안녕하세요 해커그라운드 조직 의원회입니다.
클라우드 스킬 챌린지를 신청하고 진행해주시길 바랍니다.
