### ISSUE TITLE
[DP-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by lee1010yj** [microsoft/hackers-ground#356]
## 챌린지 코드

깃헙 ID
https://github.com/lee1010yj

Microsoft Learn 프로필 링크

https://learn.microsoft.com/ko-kr/users/yejinlee-6234/challenges

## 챌린지 완료 인증 

![image](https://github.com/microsoft/hackers-ground/assets/136915325/571cbb79-db63-460e-b9aa-4b0ed5da3609)

**Comment by isp829** [comment]
안녕하세요 해커그라운드 조직 의원회입니다.
클라우드 스킬 챌린지를 신청하고 진행해주시길 바랍니다.
