### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by s2jw** [microsoft/hackers-ground#495]
* 깃헙 ID
s2jw

* Microsoft Learn 프로필 링크
https://learn.microsoft.com/ko-kr/users/jwchoi-7435/

* 클라우드 스킬 챌린지 토픽/코드
애저 기초 (AZ-900)

<img width="663" alt="스크린샷 2023-06-18 20 08 15" src="https://github.com/microsoft/hackers-ground/assets/113405841/7621f9a5-5623-48aa-a4ff-27b4b22b6cd3">

**Comment by isp829** [comment]
안녕하세요 해커그라운드 조직 의원회 입니다.
디스코드 참여 부탁드립니다.
https://discord.gg/bnpvGuE2
