### ISSUE TITLE
[DP-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by churaly** [microsoft/hackers-ground#507]
**👆👆👆 상단의 제목에 챌린지 코드를 반드시 적어 주세요 👆👆👆**

**반드시 이슈 하나당 챌린지 하나만 작성해 주세요**

## 챌린지 코드
* `DP-900`: 애저 데이터 기초 챌린지

## 챌린지 디테일

* 깃헙 ID

  > churaly 

* Microsoft Learn 프로필 링크

  > https://learn.microsoft.com/ko-kr/users/52593736/

* 클라우드 스킬 챌린지 토픽/코드

  > DP-900 애저 데이터 기초 완료 
## 챌린지 완료 인증 예시

![스크린샷 2023-06-18 204316](https://github.com/microsoft/hackers-ground/assets/135798720/ae58ce1d-d012-4f63-b996-25e27b098804)

**Comment by isp829** [comment]
안녕하세요 해커그라운드 조직 의왼회입니다.
현재 churaly 닉네임을 한 디스코드 계정이 채널에 3개있어서 자주 사용하시는 계정으로 깃허브 id인증에 채팅하나만 부탁드립니다.
