### ISSUE TITLE
[**챌린지 코드**] 챌린지 완료 인증

### ISSUE THREAD

**Issue by oasisday** [microsoft/hackers-ground#542]
**👆👆👆 상단의 제목에 챌린지 코드를 반드시 적어 주세요 👆👆👆**

**반드시 이슈 하나당 챌린지 하나만 작성해 주세요**

## 챌린지 코드

* `AZ-900`: 애저 기초 챌린지

## 챌린지 디테일

* 깃헙 ID
https://github.com/oasisday

* Microsoft Learn 프로필 링크
https://learn.microsoft.com/ko-kr/users/53042470/](https://learn.microsoft.com/ko-kr/users/oasisday-0240/)

* 클라우드 스킬 챌린지 토픽/코드
애저 기초 (AZ-900),

## 챌린지 완료 인증 예시
![image](https://github.com/microsoft/hackers-ground/assets/105856447/2753308c-31c2-4427-9677-3b141a40f6ae)

**Comment by isp829** [comment]
이슈 수정말고 새로 올려주시길 바랍니다.
클스챌 신청을 하시고 챌린지를 진행 부탁드립니다.
디스코드주소:  https://discord.gg/bnpvGuE2
