### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by oasisday** [microsoft/hackers-ground#543]
**👆👆👆 상단의 제목에 챌린지 코드를 반드시 적어 주세요 👆👆👆**

**반드시 이슈 하나당 챌린지 하나만 작성해 주세요**

## 챌린지 코드

* `AZ-900`: 애저 기초 챌린지

## 챌린지 디테일

* 깃헙 ID
https://github.com/oasisday

* Microsoft Learn 프로필 링크
https://learn.microsoft.com/ko-kr/users/53042470/](https://learn.microsoft.com/ko-kr/users/oasisday-0240/)

* 클라우드 스킬 챌린지 토픽/코드
애저 기초 (AZ-900),

## 챌린지 완료 인증 예시
![image](https://github.com/microsoft/hackers-ground/assets/105856447/2753308c-31c2-4427-9677-3b141a40f6ae)

**Comment by chadata** [comment]
AZ-900 과정이 수료한 것이 확인되지 않습니다.
본 과정을 모두 완료하시고 다시 올려주세요.

**Comment by isp829** [comment]
앞에 예시 링크부분 지워주고 본인것만 올려주세요
