### ISSUE TITLE
[DP-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by oasisday** [microsoft/hackers-ground#545]
**👆👆👆 상단의 제목에 챌린지 코드를 반드시 적어 주세요 👆👆👆**

**반드시 이슈 하나당 챌린지 하나만 작성해 주세요**

## 챌린지 코드

* `DP-900`: 애저 데이터 기초 챌린지

## 챌린지 디테일

* 깃헙 ID
https://github.com/oasisday

* Microsoft Learn 프로필 링크
https://learn.microsoft.com/ko-kr/users/53042470/](https://learn.microsoft.com/ko-kr/users/oasisday-0240/)

* 클라우드 스킬 챌린지 토픽/코드
애저 데이터 기초 (DP-900),

## 챌린지 완료 인증 예시
![image](https://github.com/microsoft/hackers-ground/assets/105856447/fd9c20ee-9555-425a-ae19-993f15d0483f)

**Comment by swookjy** [comment]
Microsoft Learn 프로필 링크에서 트로피를 확인할 수 없습니다. 이슈를 닫습니다.

**Comment by isp829** [comment]
앞에 예시 링크부분 지워주고 본인것만 올려주세요
