### ISSUE TITLE
[SC-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by hyewonm** [microsoft/hackers-ground#55]
깃헙 ID : hyewonm

Microsoft Learn 프로필 링크 : https://learn.microsoft.com/ko-kr/users/12345678/

클라우드 스킬 챌린지 토픽/코드 보안 기초 : (SC-900)

**Comment by swookjy** [comment]
@hyewonm Microsoft Learn 프로필 링크를 통해 트로피를 확인할 수 없습니다.
다시 한번 확인해주세요. 이슈를 닫습니다.
