### ISSUE TITLE
[MS-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by s2jw** [microsoft/hackers-ground#575]
## 챌린지 코드
MS-900

## 챌린지 디테일
* 깃헙 ID
s2jw

* Microsoft Learn 프로필 링크
https://learn.microsoft.com/ko-kr/users/jwchoi-7435/

* 클라우드 스킬 챌린지 토픽/코드
MS-900

## 챌린지 완료 인증 예시
<img width="663" alt="스크린샷 2023-06-18 23 49 45" src="https://github.com/microsoft/hackers-ground/assets/113405841/c5d5bc4f-9314-48ec-8585-33b6742fc8d2">

**Comment by isp829** [comment]
안녕하세요 해커그라운드 조직 의원회입니다.
디스코드 참여 부탁드립니다.
https://discord.gg/bnpvGuE2
