### ISSUE TITLE
[AZ-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by jchyng** [microsoft/hackers-ground#7]
1. 깃헙ID
https://github.com/jchyng

2. MS Learn Profile
 https://learn.microsoft.com/ko-kr/users/56392905/

4. 클라우드 스킬 챌린지 토픽
 애저 기초 (AZ-900) 챌린지

**Comment by justinyoo** [comment]
@jchyng 별도로 챌린지 완료 인증 방법에 대한 안내가 나갈 예정입니다. 그 때 까지 기다려 주세요.

**Comment by justinyoo** [comment]
@jchyng 제목을 변경하도록 하겠습니다. 다음부터는 이슈 생성시 제공되는 템플릿을 기초로 만들어 주세요.
