### ISSUE TITLE
[SC-900] 챌린지 완료 인증

### ISSUE THREAD

**Issue by kairos-hk** [microsoft/hackers-ground#8]
1, 깃헙 ID : https://github.com/kairos-hk
2, MS Learn : https://learn.microsoft.com/ko-kr/users/37863358
3, 보안 기초 (SC-900) 챌린지

**Comment by justinyoo** [comment]
@kairos-hk 이슈 하나당 챌린지 하나입니다. 현재 이슈 하나에 챌린지 두 개를 인증하셨는데요, 이 이슈는 보안 기초(SC-900)로 변경할테니, 애저 기초(AZ-900)은 별도의 이슈로 다시 등록해 주세요.
